version: "3"

services:
  pgsql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    container_name: "pgsql"
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  adminer:
    image: adminer
    restart: always
    depends_on:
      - pqsql
    ports:
      - 8080:8080
